version: '3.7'

services:
    nginx:
        image: nginx:1.17.5-alpine
        restart: on-failure
        depends_on:
            - php
        ports:
            - 127.0.0.1:8000:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/app:ro
    php:
        build:
            context: docker/php
            dockerfile: Dockerfile
        restart: on-failure
        depends_on:
            - postgres
        user: ${USERID}:${GROUPID}
        environment:
            XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST}
            PHP_IDE_CONFIG: serverName=Docker
            COMPOSER_HOME: /tmp
        working_dir: /app
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./docker/php/php-cli.ini:/usr/local/etc/php/php-cli.ini:ro
            - ./:/app

    postgres:
        image: postgres:13.3-alpine
        restart: on-failure
        ports:
            - 127.0.0.1:5432:5432
        environment:
            TZ: Europe/Moscow
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/postgresql:/var/lib/postgresql

    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - 127.0.0.1:${PGADMIN_PORT:-5050}:80

volumes:
    pgadmin: