version: '3.7'

services:
    nginx:
        image: nginx:1.17.5-alpine
        restart: on-failure
        depends_on:
            - php
        ports:
            - "127.0.0.1:8000:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/app:ro
    php:
        image: manull/php-oci:8.1.8-fpm-11g
        restart: on-failure
        depends_on:
            - postgres
        user: ${USERID}:${GROUPID}
        environment:
            NLS_LANG: AMERICAN_AMERICA.AL32UTF8
            XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST}
            PHP_IDE_CONFIG: serverName=Docker
            COMPOSER_HOME: /tmp
        working_dir: /app
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./docker/php/php-cli.ini:/usr/local/etc/php/php-cli.ini:ro
            - ./:/app
        extra_hosts:
            - ${DATABASE_IP}:${DATABASE_IP}
